# Generated by Django 4.2.7 on 2026-02-13 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='ad/')),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_ad',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.ImageField(null=True, upload_to='cover/')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('translator', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('press', models.CharField(blank=True, max_length=50, null=True)),
                ('page_count', models.IntegerField(default=0)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn', models.CharField(blank=True, max_length=50, null=True)),
                ('pub_date', models.DateField(null=True)),
                ('online_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('0', '上架'), ('1', '下架')], default='0', max_length=1)),
                ('repertory', models.IntegerField(default=0)),
                ('score', models.CharField(default=0, max_length=10)),
                ('layout', models.CharField(blank=True, max_length=10, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('pv', models.IntegerField(default=0)),
                ('recommend_count', models.IntegerField(default=0)),
                ('wish_count', models.IntegerField(default=0)),
                ('collect_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'b_book',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField(blank=True, default=-1, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_classification',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('log_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_error_log',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('ua', models.CharField(blank=True, max_length=200, null=True)),
                ('log_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_login_log',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_notice',
            },
        ),
        migrations.CreateModel(
            name='OpLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('re_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('re_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('re_url', models.CharField(blank=True, max_length=200, null=True)),
                ('re_method', models.CharField(blank=True, max_length=10, null=True)),
                ('re_content', models.CharField(blank=True, max_length=200, null=True)),
                ('access_time', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'b_op_log',
            },
        ),
        migrations.CreateModel(
            name='ReadingEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('cover', models.ImageField(null=True, upload_to='event/')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('0', '未开始'), ('1', '进行中'), ('2', '已结束')], default='0', max_length=1)),
            ],
            options={
                'db_table': 'b_reading_event',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '封号')], default='0', max_length=1)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.FileField(null=True, upload_to='avatar/')),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('push_email', models.CharField(blank=True, max_length=40, null=True)),
                ('push_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('admin_token', models.CharField(blank=True, max_length=32, null=True)),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'b_user',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('record_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_record', to='myapp.book')),
                ('classification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='myapp.classification')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_record', to='myapp.user')),
            ],
            options={
                'db_table': 'b_record',
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('liked_users', models.ManyToManyField(blank=True, related_name='liked_posts', to='myapp.user')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_community_post', to='myapp.user')),
            ],
            options={
                'db_table': 'b_community_post',
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_comment', to='myapp.readingevent')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='myapp.communitypost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_community_comment', to='myapp.user')),
            ],
            options={
                'db_table': 'b_community_comment',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('comment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_comment', to='myapp.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='myapp.user')),
            ],
            options={
                'db_table': 'b_comment',
            },
        ),
        migrations.CreateModel(
            name='BorrowLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(blank=True, max_length=2, null=True)),
                ('log_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_borrow_log', to='myapp.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_borrow_log', to='myapp.user')),
            ],
            options={
                'db_table': 'b_borrow_log',
            },
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('borrow_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('expect_time', models.DateTimeField(null=True)),
                ('return_time', models.DateTimeField(null=True)),
                ('delayed', models.BooleanField(blank=True, default=False, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_borrow', to='myapp.book')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_borrow', to='myapp.user')),
            ],
            options={
                'db_table': 'b_borrow',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_book', to='myapp.classification'),
        ),
        migrations.AddField(
            model_name='book',
            name='collect',
            field=models.ManyToManyField(blank=True, related_name='collect_books', to='myapp.user'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(blank=True, to='myapp.tag'),
        ),
        migrations.AddField(
            model_name='book',
            name='wish',
            field=models.ManyToManyField(blank=True, related_name='wish_books', to='myapp.user'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='banner/')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_banner', to='myapp.book')),
            ],
            options={
                'db_table': 'b_banner',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('default', models.BooleanField(blank=True, default=False, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='myapp.user')),
            ],
            options={
                'db_table': 'b_address',
            },
        ),
    ]
