# Generated by Django 4.2.7 on 2026-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='myapp.user'),
        ),
    ]
